### ISSUE TITLE
VSCode Web

### ISSUE THREAD

**Issue by tani** [nuxtlabs/vscode-mdc#25]
Hi, thank you for the great extension.
I would like to use this extension on github.dev and vscode.dev .
Nowadays, VSCode is not only for the native/ local installation but also for the Cloud service.
Unfortunately, This extension is not work for VSCode Web because there are no properties in package.json to allow running on VSCode Web. Please consider to add them.

For the detail, please read the documentation https://code.visualstudio.com/api/extension-guides/web-extensions

**Comment by farnabaz** [comment]
v0.1.8 is now available in web editors 🙂 

<img width="691" alt="Screenshot 2022-09-14 at 09 31 14" src="https://user-images.githubusercontent.com/2047945/190089921-4c9c9c2e-1cff-47c5-8b9b-a35ab9e05221.png">

**Comment by tani** [comment]
Yay! Thank you so much!
