### ISSUE TITLE
Usage with Monaco?

### ISSUE THREAD

**Issue by CapitaineToinon** [nuxtlabs/vscode-mdc#37]
Hello !

I've been looking at various markdown supersets and how to integrate them on a website through editors such as the monaco editor. As far as I understand, while monaco powers vscode under the hood, it's not possible to directly use such an extension with monaco. I'd love some direction if I'm wrong on that point though.

Allowing for this would be incredibly powerful in my opinion. Being able to store MDC content in a database and edit it through an admin dashboard would be great. 

This project doesn't have discussions open so I'm opening a ticket instead, sorry about that.

Thanks for the help !

**Comment by Atinux** [comment]
I believe @farnabaz made it work inside an embedded Monaco Editor

**Comment by CapitaineToinon** [comment]
I felt down quite the rabbit hole looking into this. Apparently vscode supports text-mate configuration files out of the box but monaco does not. Seems to be possible to load those anyway using some wasm regex library but all the examples are old and not maintained. If someone has an example up and running, I would love to be able to take a look.

**Comment by farnabaz** [comment]
Hey @CapitaineToinon,
Sadly, monaco does not support text-mate languages, instead it has its own way that called [monarch](https://microsoft.github.io/monaco-editor/monarch.html).

You can use [`nuxtlabs/monarch-mdc`](https://github.com/nuxtlabs/monarch-mdc) to allow highlighting MDC in monaco.

**Comment by CapitaineToinon** [comment]
Oh okay seems to be accessible through npm and installs just fine. Thanks, will try that! 

https://www.npmjs.com/package/@nuxtlabs/monarch-mdc

**Comment by farnabaz** [comment]
Yeah, may bad. It is not yet public, you can use it directly from npm https://www.npmjs.com/package/@nuxtlabs/monarch-mdc

**Comment by adamdehaven** [comment]
@farnabaz any plan to open source the `monarch-mdc` repo? I'm trying to figure out if I can support a formatting extension for monaco specifically for MDC

**Comment by atinux** [comment]
I am open to open source it if you want to make it public @farnabaz

**Comment by farnabaz** [comment]
The source is now available: https://github.com/nuxtlabs/monarch-mdc
